animals = ['lion', 'tiger', 'bear', 'wolf', 'rabbit']
animals.append('budgie')
print(animals)
animals.append('cat')
print(animals)
animals.insert(0, 'fish')
print(animals)
animals.insert(1, 'dog')
print(animals)
del animals[0]
print(animals)
poped_animal = animals.pop()
print(animals)
print(poped_animal)
animals.remove('dog')
print(animals)
animals.sort()
print(animals)
animals.sort(reverse=True)
print(animals)
print(sorted(animals))
animals.reverse()
print(animals)
print(len(animals))